<Project Sdk="Godot.NET.Sdk/4.3.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>UltraPong</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Cursor.cs" />
    <Compile Remove="Game.cs" />
    <Compile Remove="Server.cs" />
    <Compile Remove="Client.cs" />
    <Compile Remove="ClockSync.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="ballStats.json" />
    <Content Include="playerStats.json" />
    <Content Include="rcedit-x64.exe" />
    <Content Include="userStats.json" />
    <Content Include=".gitignore" />
  </ItemGroup>
</Project>