<Project Sdk="Godot.NET.Sdk/4.3.0">
  <PropertyGroup>
    <TargetFramework>net60</TargetFramework>
    <RootNamespace>UltraPong</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Cursor.cs" />
    <Compile Remove="Game.cs" />
    <Compile Remove="Server.cs" />
    <Compile Remove="Client.cs" />
    <Compile Remove="ClockSync.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="addons\Holepunch\holepunch.gd" />
    <Content Include="addons\Holepunch\holepunch_node.gd" />
    <Content Include="addons\Holepunch\plugin.cfg" />
    <Content Include="ballStats.json" />
    <Content Include="playerStats.json" />
    <Content Include="userStats.json" />
    <Content Include=".gitignore" />
  </ItemGroup>
</Project>