<Project Sdk="Godot.NET.Sdk/4.2.0">
  <PropertyGroup>
    <TargetFramework>net60</TargetFramework>
    <RootNamespace>UltraPong</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Cursor.cs" />
    <Compile Remove="Game.cs" />
    <Compile Remove="Server.cs" />
    <Compile Remove="Client.cs" />
    <Compile Remove="ClockSync.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
  </ItemGroup>
</Project>